name = "NTTs"
uuid = "355ed90f-8f14-42c1-a87f-2eca0abd88af"
authors = ["Alex Pan"]
version = "1.0.0-DEV"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"

[compat]
BitIntegers = "0.3.2"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
